name: Docker

on:
  push:
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image 
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            DOCKER_TAG=${{ github.event.inputs.docker_tag }}
          elif [[ "${{ github.event_name }}" == "push" && "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            DOCKER_TAG=$(echo ${GITHUB_REF#refs/tags/})
            docker build --push --tag ${{ secrets.DOCKER_USERNAME }}/bypy:latest .
          else
            DOCKER_TAG=${{ github.event.pull_request.number }}
          fi
          docker build --push --tag ${{ secrets.DOCKER_USERNAME }}/bypy:$DOCKER_TAG .
